### ISSUE TITLE
access keeweb config

### ISSUE THREAD

**Issue by madcoda9000** [viossat/docker-keeweb#2]
Hello,

I am using this compose:

```
name: keeweb
services:
    keeweb:
        ports:
            - 3080:80
        environment:
            - WEBDAV_USERNAME=sheimann
            - WEBDAV_PASSWORD=heineu@900!
        volumes:
            - /volume1/docker/keeweb/webdav:/usr/share/nginx/html/webdav
            - /volume1/docker/keeweb/web:/usr/share/nginx/html/keeweb
        image: viossat/keeweb
```

As you can see I am trying to mount the keeweb folder so that i can modify the keeweb config. I'v tried this because I've seen that your dockerfile copies keeweb from git to /usr/share/nginx/html. But it did not work. The folder is empty.

So, how can i modify the keeweb config?

by the way: your image is working like a charm!
